import { Resend } from 'resend';
import type { BetDecision } from './decision';

const resend = new Resend(process.env.RESEND_API_KEY);

export interface PickEmailData {
  homeTeam: string;
  awayTeam: string;
  league: string;
  kickoff: string;
  market: string;
  odds?: number;
  confidence: number;
  edgePct?: number;
  reason: string;
}

function leagueLabel(slug: string) {
  const map: Record<string, string> = {
    'premier-league': 'Premier League',
    'la-liga': 'La Liga',
    'serie-a': 'Serie A',
    'bundesliga': 'Bundesliga',
    'ligue-1': 'Ligue 1',
  };
  return map[slug] ?? slug.replace(/-/g, ' ');
}

function pickRow(p: PickEmailData, i: number) {
  const kickoff = new Date(p.kickoff);
  const timeStr = kickoff.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
  const dateStr = kickoff.toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' });
  const confColor = p.confidence >= 75 ? '#10b981' : '#f59e0b';

  return `
    <tr>
      <td style="padding:14px 0;border-bottom:1px solid #1e1e30;">
        <table width="100%" cellpadding="0" cellspacing="0">
          <tr>
            <td>
              <div style="font-size:10px;color:#52526e;text-transform:uppercase;letter-spacing:0.08em;margin-bottom:2px;">
                #${i + 1} · ${leagueLabel(p.league)} · ${dateStr} ${timeStr}
              </div>
              <div style="font-size:15px;font-weight:700;color:#f1f1f8;margin-bottom:4px;">
                ${p.homeTeam} vs ${p.awayTeam}
              </div>
              <div style="font-size:13px;color:#06b6d4;font-weight:600;margin-bottom:4px;">
                ${p.market}${p.odds ? ` <span style="color:#8b8ba8;font-weight:400;">@ ${p.odds.toFixed(2)}</span>` : ''}
              </div>
              <div style="font-size:12px;color:#8b8ba8;line-height:1.5;">${p.reason}</div>
            </td>
            <td style="text-align:right;vertical-align:top;padding-left:12px;white-space:nowrap;">
              <div style="font-size:20px;font-weight:800;color:${confColor};">${p.confidence}%</div>
              ${p.edgePct !== undefined ? `<div style="font-size:11px;color:#10b981;">+${p.edgePct}% edge</div>` : ''}
            </td>
          </tr>
        </table>
      </td>
    </tr>
  `;
}

function buildEmailHtml(picks: PickEmailData[], date: string) {
  const rows = picks.map((p, i) => pickRow(p, i)).join('');
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#080811;font-family:system-ui,-apple-system,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#080811;min-height:100vh;padding:32px 16px;">
    <tr><td align="center">
      <table width="100%" style="max-width:560px;" cellpadding="0" cellspacing="0">

        <!-- Header -->
        <tr><td style="padding-bottom:24px;">
          <table cellpadding="0" cellspacing="0">
            <tr>
              <td style="background:linear-gradient(135deg,#10b981,#06b6d4);border-radius:10px;width:36px;height:36px;text-align:center;vertical-align:middle;">
                <span style="font-size:13px;font-weight:800;color:#000;">GE</span>
              </td>
              <td style="padding-left:10px;">
                <div style="font-size:17px;font-weight:800;color:#f1f1f8;">GoalEdge</div>
                <div style="font-size:11px;color:#52526e;">Daily Picks Alert · ${date}</div>
              </td>
            </tr>
          </table>
        </td></tr>

        <!-- Card -->
        <tr><td style="background:#0f0f1a;border:1px solid rgba(255,255,255,0.08);border-radius:16px;padding:24px;">

          <div style="font-size:18px;font-weight:800;color:#f1f1f8;margin-bottom:4px;">
            ${picks.length} High-Confidence ${picks.length === 1 ? 'Pick' : 'Picks'} Today
          </div>
          <div style="font-size:13px;color:#8b8ba8;margin-bottom:20px;">
            Model edge confirmed — ${picks.filter(p => p.confidence >= 70).length} strong bet${picks.filter(p => p.confidence >= 70).length !== 1 ? 's' : ''}, ${picks.filter(p => p.confidence < 70).length} small stake.
          </div>

          <table width="100%" cellpadding="0" cellspacing="0">
            ${rows}
          </table>

          <div style="margin-top:20px;padding-top:16px;border-top:1px solid #1e1e30;font-size:11px;color:#52526e;line-height:1.6;">
            Picks are generated by a Poisson model using real league standings data.
            Always bet responsibly. These are model outputs, not financial advice.
          </div>
        </td></tr>

        <!-- Footer -->
        <tr><td style="padding-top:20px;text-align:center;font-size:11px;color:#35354d;">
          GoalEdge · Powered by ai-sports.io &amp; Anthropic Claude<br>
          <a href="https://goaledge-blush.vercel.app/settings" style="color:#52526e;">Manage alerts</a>
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>
  `.trim();
}

export async function sendPicksAlert(picks: PickEmailData[], toEmail: string) {
  const date = new Date().toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });

  const { data, error } = await resend.emails.send({
    from: 'GoalEdge <onboarding@resend.dev>',
    to: toEmail,
    subject: `⚽ ${picks.length} GoalEdge ${picks.length === 1 ? 'Pick' : 'Picks'} for ${date}`,
    html: buildEmailHtml(picks, date),
  });

  if (error) throw new Error(error.message);
  return data;
}
